# Test Panorama from https://github.com/rammpeter/Panorama_Gem
# Requires:
#  - prebuilt database image with test users

image: jruby:9.2.8.0

variables:
  TEST_HOST: "oracle-db"

# Separate stages because pending jobs get stuck after one hour (hard limit)
stages:
  - test
  - build
  - deploy

.tests:
  script:
    # Set Timezone to CET first
    - sh -c "echo 'Europe/Berlin' > /etc/timezone"
    - sh -c "rm /etc/localtime && ln -s /usr/share/zoneinfo/Europa/Berlin /etc/localtime"
    - dpkg-reconfigure -f noninteractive tzdata
    - date
    - bundle install
    - bundle exec rails test
  #    - sh -c "cd Panorama_Gem && rake test TEST=test/system/spec_additions_test.rb"
  artifacts:
    when: always
    paths:
      #     - last_test.log
      - test/log/
      - tmp/screenshots/
    expire_in: 1 month


.tests_SQLITE:
  extends: .tests
  variables:
    TRIXX_DB_TYPE: "SQLITE"

.tests_ORACLE:
  extends: .tests
  variables:
    TRIXX_DB_TYPE: "ORACLE"
    TEST_SERVICENAME: "ORCL"

test_sqlite:
  stage: test
  extends: .tests_SQLITE

test_oracle_11.2:
  stage: test
  extends: .tests_ORACLE
  services:
    - name: dockerhub.osp-dd.de/pramm/oracle/database_prebuilt:11.2.0.4-ee
      alias: oracle-db
  script:
    - sh -c "echo ORACLE-Teil"
    - docker ps



build_trixx:
  stage: build
  script:
    - sh -c "echo Build"

