# Reduced Pipeline

image: git.osp-dd.de:5005/main/trixx/kafka-jruby:9.2.13.0-jdk14

variables:
  CI_DEBUG_SERVICES: trace
  TRIXX_KAFKA_SEED_BROKER: localhost:9092
  TEMP_DOCKER_IMAGE: git.osp-dd.de:5005/main/trixx:master-ci-temp


# Separate stages because pending jobs get stuck after one hour (hard limit)
stages:
  - post_build

.docker_test:
  script:
    # dummy action up to get service running
    - env | sort

docker_test_oracle_12.1:
  stage: post_build
  extends: .docker_test
  services:
    - name: git.osp-dd.de:5005/pramm/panorama_gem_ci/database_prebuilt:12.2.0.1-ee
      alias: oracle-db
    - name: $TEMP_DOCKER_IMAGE
      alias: trixx
  variables:
    TRIXX_DB_TYPE: ORACLE
    TRIXX_DB_USER: trixx
    TRIXX_DB_PASSWORD: trixx
    TRIXX_DB_URL: "oracle-db:1521/ORCLPDB1"


