# Reduced Pipeline

image: git.osp-dd.de:5005/main/trixx/kafka-jruby:9.2.13.0-jdk14

variables:
  CI_DEBUG_SERVICES: trace
  TRIXX_KAFKA_SEED_BROKER: localhost:9092
  TEMP_DOCKER_IMAGE: git.osp-dd.de:5005/main/trixx:master-ci-temp


# Separate stages because pending jobs get stuck after one hour (hard limit)
stages:
  - post_build

.docker_test:
  script:
    - podman --events-backend=file login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - podman --events-backend=file pull $TEMP_DOCKER_IMAGE
    - podman --events-backend=file --cgroup-manager=cgroupfs run --rm
      -e TRIXX_DB_TYPE=ORACLE -e TRIXX_DB_USER=trixx -e TRIXX_DB_PASSWORD=trixx -e TRIXX_DB_URL=$TRIXX_DB_URL -e TRIXX_DB_SYS_PASSWORD=oracle
      -e TRIXX_KAFKA_SEED_BROKER=$TRIXX_KAFKA_SEED_BROKER $TEMP_DOCKER_IMAGE bundle exec rake ci_preparation:create_user
    - podman --events-backend=file --cgroup-manager=cgroupfs run -d --rm --name=trixx -p8080:8080
      -e TRIXX_DB_TYPE=ORACLE -e TRIXX_DB_USER=trixx -e TRIXX_DB_PASSWORD=trixx -e TRIXX_DB_URL=$TRIXX_DB_URL
      -e TRIXX_KAFKA_SEED_BROKER=$TRIXX_KAFKA_SEED_BROKER $TEMP_DOCKER_IMAGE
    - sleep 5
    - podman ps
    - |
      echo "
      typeset -i LOOPS=0
      echo :$LOOPS:
      while [ $LOOPS -lt 20 ]; do
        curl localhost:8080/
        if [ $? -eq 0 ]; then
          break
        fi
        LOOPS=LOOPS+1
        echo $LOOPS
        sleep 1
      done
      echo 'No access to port 8080'
      exit 1
      " | /bin/bash
    - curl localhost:8080/
    - podman stop trixx

docker_test_oracle_12.1:
  stage: post_build
  extends: .docker_test
  services:
    - name: git.osp-dd.de:5005/pramm/panorama_gem_ci/database_prebuilt:12.2.0.1-ee
      alias: oracle-db
  variables:
    TRIXX_DB_TYPE: ORACLE
    TRIXX_DB_USER: trixx
    TRIXX_DB_PASSWORD: trixx
    TRIXX_DB_URL: "oracle-db:1521/ORCLPDB1"


