# Test Panorama from https://github.com/rammpeter/Panorama_Gem
# Requires:
#  - prebuilt database image with test users

image: git.osp-dd.de:5005/main/trixx/kafka-jruby:9.2.13.0-jdk14

variables:
  CI_DEBUG_SERVICES: trace
  TRIXX_KAFKA_SEED_BROKER: localhost:9092
  TEMP_DOCKER_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME-ci-temp
  FINAL_DOCKER_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME


# Separate stages because pending jobs get stuck after one hour (hard limit)
stages:
  - post_build


.docker_test:
  script:
    - env
    - curl trixx:8080/
    # - podman --events-backend=file run --rm \
    #   -e TRIXX_DB_TYPE=ORACLE -e TRIXX_DB_USER=trixx -e TRIXX_DB_PASSWORD=trixx -e TRIXX_DB_URL=$TRIXX_DB_URL \
    #   -e TRIXX_KAFKA_SEED_BROKER=$TRIXX_KAFKA_SEED_BROKER $TEMP_DOCKER_IMAGE bundle exec rake ci_preparation:create_user
    # - podman --events-backend=file run --rm --name trixx -p8080:8080 -d \
    #   -e TRIXX_DB_TYPE=ORACLE -e TRIXX_DB_USER=trixx -e TRIXX_DB_PASSWORD=trixx -e TRIXX_DB_URL=$TRIXX_DB_URL \
    #   -e TRIXX_KAFKA_SEED_BROKER=$TRIXX_KAFKA_SEED_BROKER $TEMP_DOCKER_IMAGE
    # - podman stop trixx

docker_test_oracle_12.1:
  stage: post_build
  extends: .docker_test
  services:
    - name: git.osp-dd.de:5005/pramm/panorama_gem_ci/database_prebuilt:12.2.0.1-ee
      alias: oracle-db
    - name: $TEMP_DOCKER_IMAGE
      alias: trixx
  variables:
    CI_DEBUG_SERVICES: trace
    TRIXX_DB_TYPE: ORACLE
    TRIXX_DB_USER: trixx
    TRIXX_DB_PASSWORD: trixx
    TRIXX_DB_URL: "oracle-db:1521/ORCLPDB1"


