# Test Panorama from https://github.com/rammpeter/Panorama_Gem
# Requires:
#  - prebuilt database image with test users

image: jruby:9.2.8.0

variables:
  TEST_HOST: "oracle-db"

# Separate stages because pending jobs get stuck after one hour (hard limit)
stages:
  - test
  - build
  - deploy

.tests:
  variables:
    RAILS_ENV: "test"
  script:
    # Set Timezone to CET first
    - sh -c "echo 'Europe/Berlin' > /etc/timezone"
    - sh -c "rm /etc/localtime && ln -s /usr/share/zoneinfo/Europa/Berlin /etc/localtime"
    - dpkg-reconfigure -f noninteractive tzdata
    - date
    - java -version
    - gem install bundler
    - bundle config set deployment 'true'
    - bundle install --jobs 4
    - bundle exec rake ci_preparation:create_test_user
    - bundle exec rails db:migrate RAILS_ENV=test
    - >
      if [ "$TRIXX_DB_TYPE" == "ORACLE" ]; then
        # Check if db:rollback is functional + restore migration
        bundle exec rails db:migrate RAILS_ENV=test VERSION=0 && bundle exec rails db:migrate RAILS_ENV=test
      fi
    - bundle exec rails test
  artifacts:
    when: always
    paths:
      #     - last_test.log
      - log/
      - tmp/screenshots/
    expire_in: 1 month


.tests_SQLITE:
  extends: .tests
  variables:
    TRIXX_DB_TYPE: "SQLITE"

.tests_ORACLE:
  extends: .tests
  variables:
    TRIXX_DB_TYPE: "ORACLE"
    TRIXX_DB_SYSTEM_PASSWORD: "oracle"
    TEST_SERVICENAME: "ORCL"

test_sqlite:
  stage: test
  extends: .tests_SQLITE

test_oracle_11.2:
  stage: test
  extends: .tests_ORACLE
  services:
    - name: dockerhub.osp-dd.de/pramm/oracle/database_prebuilt:11.2.0.4-ee
      alias: oracle-db
  variables:
    TRIXX_DB_URL: "oracle-db:1521/ORCL"


build_trixx:
  stage: build
  script:
    - sh -c "echo Build"

