# docker-compose.yml for Kafka installation from wurstmeister
# change KAFKA_ADVERTISED_HOST_NAME to your host / IP
# run commands for:
# start cluster:      docker-compose -f kafka_docker-compose.yml up
# add more brokers:   docker-compose -f kafka_docker-compose.yml scale kafka=3
# destroy cluster:    docker-compose -f kafka_docker-compose.yml stop

version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    #build: .
    ports:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: lap-ramm-macpro.osp-dd.de
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
