version: '3'
services:
  trixx-frontend:
    build:
      context: ../frontend
      dockerfile: ../docker/frontend/Dockerfile.dev
    volumes:
      - ../frontend:/app
    ports:
      - "8080:8080"
    environment:
      VUE_APP_BACKEND_URL: http://localhost:3000

  trixx-backend:
    build:
      context: ..
      dockerfile: ./docker/backend/Dockerfile.dev
    volumes:
      - ..:/app
    ports:
      - "3000:3000"
    environment:
      DB_PASSWORD: test
      DB_TYPE: SQLITE
      RAILS_MAX_THREADS: 50
      INFO_CONTACT_PERSON: Max Mustermann (max.mustermann@osp-trixx.de)

networks:
  default:
    external:
      name: public
