version: '3'
services:
  movex-cdc-frontend:
    build:
      context: ../frontend
      dockerfile: ../docker/frontend/Dockerfile.dev
    volumes:
      - ../frontend:/app
    ports:
      - "8080:8080"
    environment:
      VUE_APP_BACKEND_URL: http://localhost:3000

  movex-cdc-backend:
    build:
      context: ..
      dockerfile: ./docker/backend/Dockerfile.dev
    volumes:
      - ..:/app
    ports:
      - "3000:3000"
    environment:
      DB_USER: movex
      DB_PASSWORD: pass
      DB_TYPE: ORACLE
      DB_URL: oracle:1521/ORCLPDB1

networks:
  default:
    external:
      name: public