# SQLite. Versions 3.8.0 and up are supported.
#   gem 'activerecord-jdbcsqlite3-adapter'
#
# Configure Using Gemfile
# gem 'activerecord-jdbcsqlite3-adapter'
#
default: &default
  adapter: <%=
    case Trixx::Application.config.trixx_db_type
      when 'ORACLE' then 'oracle_enhanced'
      when 'SQLITE' then 'sqlite3'
    else
      raise "Unsupported value for Trixx::Application.config.trixx_db_type: '#{Trixx::Application.config.trixx_db_type}'"
    end
  %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 20 } %>

  driver: <%=
    case Trixx::Application.config.trixx_db_type
    when 'ORACLE' then 'oracle.jdbc.driver.OracleDriver'
    end
  %>
  username: <%= Trixx::Application.config.trixx_db_user %>
  password: <%= Trixx::Application.config.trixx_db_password %>
  url: <%=
    case Trixx::Application.config.trixx_db_type
    when 'ORACLE' then "jdbc:oracle:thin:@#{Trixx::Application.config.trixx_db_url }"
    end
  %>

  cursor_sharing: <%=
    case Trixx::Application.config.trixx_db_type
    when 'ORACLE' then 'exact'
    end
  %>

development:
  <<: *default

  database: <%=
    case Trixx::Application.config.trixx_db_type
    when 'SQLITE' then 'db/development.sqlite3'
    end
  %>

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test:
  <<: *default
  database: <%=
    case Trixx::Application.config.trixx_db_type
    when 'SQLITE' then 'db/test.sqlite3'
    end
  %>

production:
  <<: *default
  database: <%=
    case Trixx::Application.config.trixx_db_type
    when 'SQLITE' then 'db/production.sqlite3'
    end
  %>

